version: "3.0"

services:

  backend:
    context: .
    image: backend
    env_file: docker-compose.env
    environment:
      PORT: 3000
    ports:
      - "3000:3000"

  nats:
    image: nats
    ports:
      - "4222:4222"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db